<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionAccessSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permission_accesses')->insert([
            ['permission_id' => 1, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 1, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 1, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 1, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 1, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 1, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 2, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 2, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 2, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 2, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 2, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 2, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 3, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 3, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 3, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 3, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 3, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 3, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 4, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 4, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 4, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 4, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 4, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 4, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 5, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 5, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 5, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 5, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 5, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 5, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 6, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 6, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 6, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 6, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 6, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 6, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 7, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 7, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 7, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 7, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 7, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 7, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 8, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 8, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 8, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 8, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 8, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 8, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 9, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 9, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 9, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 9, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 9, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 9, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 10, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 10, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 10, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 10, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 10, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 10, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 11, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 11, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 11, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 11, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 11, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 11, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 12, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 12, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 12, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 12, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 12, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 12, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 13, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 13, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 13, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 13, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 13, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 13, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 14, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 14, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 14, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 14, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 14, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 14, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 15, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 15, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 15, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 15, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 15, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 15, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 16, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 16, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 16, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 16, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 16, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 16, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 17, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 17, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 17, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 17, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 17, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 17, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 18, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 18, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 18, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 18, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 18, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 18, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 19, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 19, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 19, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 19, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 19, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 19, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 20, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 20, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 20, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 20, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 20, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 20, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 21, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 21, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 21, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 21, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 21, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 21, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 22, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 22, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 22, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 22, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 22, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 22, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 23, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 23, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 23, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 23, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 23, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 23, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 24, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 24, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 24, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 24, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 24, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 24, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 25, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 25, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 25, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 25, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 25, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 25, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 26, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 26, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 26, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 26, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 26, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 26, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 27, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 27, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 27, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 27, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 27, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 27, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 28, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 28, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 28, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 28, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 28, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 28, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 29, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 29, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 29, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 29, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 29, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 29, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 30, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 30, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 30, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 30, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 30, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 30, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 31, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 31, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 31, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 31, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 31, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 31, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 32, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 32, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 32, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 32, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 32, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 32, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 33, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 33, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 33, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 33, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 33, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 33, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 34, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 34, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 34, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 34, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 34, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 34, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 35, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 35, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 35, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 35, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 35, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 35, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 36, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 36, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 36, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 36, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 36, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 36, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 37, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 37, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 37, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 37, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 37, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 37, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 38, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 38, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 38, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 38, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 38, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 38, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 39, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 39, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 39, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 39, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 39, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 39, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 40, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 40, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 40, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 40, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 40, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 40, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],

            ['permission_id' => 41, 'access_id' => 2, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 41, 'access_id' => 3, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 41, 'access_id' => 4, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 41, 'access_id' => 5, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 41, 'access_id' => 8, 'type' => 'WRITE', 'value' => 'ALLOW'],
            ['permission_id' => 41, 'access_id' => 9, 'type' => 'WRITE', 'value' => 'ALLOW'],
        ]);
    }
}
